name: 'Release Build'
on:
  push:
    branches:
      - main

jobs:
  release-svelte:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install app dependencies and build it
        run: yarn && yarn build
      - uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          access: 'public'
          greater-version-only: true
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
      - name: get package info
        if: steps.publish.outputs.type != 'none'
        id: package
        uses: codex-team/action-nodejs-package-info@v1
      - name: create release
        if: steps.publish.outputs.type != 'none'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package.outputs.version }}
          release_name: v${{ steps.package.outputs.version }}
          body: install the https://www.npmjs.com/package/${{ steps.package.outputs.name }}
          draft: true
          prerelease: false
